// Asset Purchase Agreement (APA) and Non-Compete Agreement Templates

export interface AgreementParty {
  name: string;
  walletAddress: string;
  email?: string;
}

export interface ListingDetails {
  title: string;
  description: string;
  price: number;
  currency: string;
  assets: string[];
}

/**
 * Generate Asset Purchase Agreement content
 */
export function generateAPAContent(
  seller: AgreementParty,
  buyer: AgreementParty,
  listing: ListingDetails,
  transactionId: string
): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `ASSET PURCHASE AGREEMENT

This Asset Purchase Agreement ("Agreement") is entered into as of ${date} by and between:

SELLER:
Name/Username: ${seller.name}
Wallet Address: ${seller.walletAddress}
${seller.email ? `Email: ${seller.email}` : ""}

BUYER:
Name/Username: ${buyer.name}
Wallet Address: ${buyer.walletAddress}
${buyer.email ? `Email: ${buyer.email}` : ""}

App Market Transaction ID: ${transactionId}

RECITALS

WHEREAS, Seller owns certain digital assets, intellectual property, and related materials described below;

WHEREAS, Buyer desires to purchase and acquire such assets from Seller;

NOW, THEREFORE, in consideration of the mutual covenants and agreements herein contained, the parties agree as follows:

1. ASSETS BEING TRANSFERRED

1.1 The following assets ("Assets") are being transferred as part of this transaction:

Project: ${listing.title}
Description: ${listing.description}

Assets Included:
${listing.assets.map((asset) => `- ${asset}`).join("\n")}

2. PURCHASE PRICE

2.1 The total purchase price for the Assets is ${listing.price} ${listing.currency} ("Purchase Price").

2.2 Payment shall be made through the App Market escrow system.

3. TRANSFER OF OWNERSHIP

3.1 Upon receipt of the full Purchase Price in escrow, Seller agrees to transfer all rights, title, and interest in and to the Assets to Buyer.

3.2 Seller represents and warrants that:
   a) Seller has full right, power, and authority to sell and transfer the Assets;
   b) The Assets are free and clear of all liens, encumbrances, and claims;
   c) The sale does not violate any agreements to which Seller is a party;
   d) All information provided about the Assets is accurate and complete.

4. INTELLECTUAL PROPERTY

4.1 All intellectual property rights associated with the Assets, including but not limited to:
   - Source code and software
   - Trademarks and branding
   - Domain names
   - Customer lists and data
   - Trade secrets and know-how

Shall be fully transferred to Buyer upon completion of this transaction.

4.2 Seller agrees not to use, copy, distribute, or create derivative works from any of the transferred intellectual property after the transfer is complete.

5. WARRANTIES AND REPRESENTATIONS

5.1 Seller warrants that:
   a) The Assets function as described in the listing;
   b) There are no undisclosed legal issues or pending litigation;
   c) Any revenue or usage statistics provided are accurate;
   d) All necessary third-party licenses are transferable.

5.2 THE ASSETS ARE PROVIDED "AS IS" AFTER TRANSFER. BUYER ACKNOWLEDGES THEY HAVE HAD THE OPPORTUNITY TO CONDUCT DUE DILIGENCE.

6. CONFIDENTIALITY

6.1 Both parties agree to maintain the confidentiality of all proprietary information exchanged during this transaction.

6.2 This obligation of confidentiality shall survive the completion of the transaction.

7. DISPUTE RESOLUTION

7.1 Any disputes arising from this Agreement shall first be addressed through the App Market dispute resolution process.

7.2 If the dispute cannot be resolved through mediation, the parties agree to binding arbitration.

8. GOVERNING LAW

8.1 This Agreement shall be governed by and construed in accordance with applicable laws.

9. ENTIRE AGREEMENT

9.1 This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, and agreements.

10. DIGITAL SIGNATURES

10.1 The parties agree that their cryptographic wallet signatures shall constitute valid and binding signatures on this Agreement.

10.2 Each party's wallet signature confirms:
   a) Their identity as the owner of the signing wallet;
   b) Their agreement to all terms and conditions herein;
   c) Their authorization to enter into this Agreement.

---

By signing this Agreement with their wallet, each party acknowledges that they have read, understood, and agree to be bound by all terms and conditions set forth herein.

SELLER SIGNATURE:
Wallet: ${seller.walletAddress}
Date: [To be signed]

BUYER SIGNATURE:
Wallet: ${buyer.walletAddress}
Date: [To be signed]

---
Generated by App Market
Transaction ID: ${transactionId}`;
}

/**
 * Generate Non-Compete Agreement content
 */
export function generateNonCompeteContent(
  seller: AgreementParty,
  buyer: AgreementParty,
  listing: ListingDetails,
  durationYears: 1 | 2 | 3,
  transactionId: string
): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const competitionScope = `
a) Create, develop, or operate any software, application, or service that is substantially similar to or competes directly with the transferred Assets;
b) Solicit or contact customers, users, or clients of the transferred Assets for the purpose of offering competing products or services;
c) Use any proprietary information, trade secrets, or know-how from the transferred Assets to benefit a competing venture;
d) Employ or solicit the employment of any key personnel associated with the transferred Assets.
  `.trim();

  return `NON-COMPETE AGREEMENT

This Non-Compete Agreement ("Agreement") is entered into as of ${date} as a supplementary agreement to the Asset Purchase Agreement for:

SELLER (Bound Party):
Name/Username: ${seller.name}
Wallet Address: ${seller.walletAddress}

BUYER (Protected Party):
Name/Username: ${buyer.name}
Wallet Address: ${buyer.walletAddress}

App Market Transaction ID: ${transactionId}

RECITALS

WHEREAS, Seller has agreed to sell certain digital assets and intellectual property to Buyer;

WHEREAS, Buyer requires protection against competition from Seller to fully realize the value of the acquired assets;

WHEREAS, Seller agrees to these restrictions as part of the overall transaction consideration;

NOW, THEREFORE, the parties agree as follows:

1. NON-COMPETITION COVENANT

1.1 For a period of ${durationYears} (${durationYears === 1 ? "one" : durationYears === 2 ? "two" : "three"}) year${durationYears > 1 ? "s" : ""} from the date of transaction completion, Seller agrees not to:

${competitionScope}

2. SCOPE

2.1 This Agreement applies to the following transferred assets:
   Project: ${listing.title}

2.2 The non-compete restrictions apply globally, as digital products and services can be accessed worldwide.

3. EXCEPTIONS

3.1 This Agreement does not prevent Seller from:
   a) Working in unrelated industries or on unrelated products;
   b) Investing passively in competing businesses (less than 5% ownership);
   c) Fulfilling prior contractual obligations disclosed before this transaction.

4. ENFORCEMENT

4.1 In the event of a breach, Buyer shall be entitled to:
   a) Injunctive relief to prevent further violations;
   b) Monetary damages including lost profits and legal fees;
   c) Specific performance of this Agreement.

5. CONSIDERATION

5.1 Seller acknowledges that the consideration for this non-compete is included in the Purchase Price and the opportunity to complete the sale.

6. REASONABLENESS

6.1 Both parties acknowledge that:
   a) The duration of ${durationYears} year${durationYears > 1 ? "s" : ""} is reasonable given the nature of the assets;
   b) The scope is limited to direct competition only;
   c) These restrictions are necessary to protect the legitimate business interests of Buyer.

7. SURVIVAL

7.1 This Agreement shall survive the completion of the asset transfer and remain in effect for the specified duration.

8. DIGITAL SIGNATURES

8.1 By signing with their wallet, each party confirms their agreement to these terms.

---

SELLER ACKNOWLEDGMENT:
I, the Seller, acknowledge that I have read and understood this Non-Compete Agreement. I agree to be bound by its terms for a period of ${durationYears} year${durationYears > 1 ? "s" : ""} from the transaction completion date.

Wallet: ${seller.walletAddress}
Date: [To be signed]

BUYER ACKNOWLEDGMENT:
I, the Buyer, acknowledge that this Non-Compete Agreement has been requested as part of the transaction.

Wallet: ${buyer.walletAddress}
Date: [To be signed]

---
Generated by App Market
Transaction ID: ${transactionId}`;
}

/**
 * Get list of assets from listing data
 */
export function getAssetsList(listing: {
  githubRepo?: string | null;
  hasDomain?: boolean;
  domain?: string | null;
  hasDatabase?: boolean;
  databaseType?: string | null;
  hasHosting?: boolean;
  hostingProvider?: string | null;
  hasVercel?: boolean;
  hasApiKeys?: boolean;
  hasDesignFiles?: boolean;
  hasDocumentation?: boolean;
  hasSocialAccounts?: boolean;
  additionalAssets?: string | null;
}): string[] {
  const assets: string[] = [];

  if (listing.githubRepo) assets.push(`GitHub Repository: ${listing.githubRepo}`);
  if (listing.hasDomain && listing.domain) assets.push(`Domain: ${listing.domain}`);
  if (listing.hasDatabase && listing.databaseType) assets.push(`Database: ${listing.databaseType}`);
  if (listing.hasHosting && listing.hostingProvider) assets.push(`Hosting: ${listing.hostingProvider}`);
  if (listing.hasVercel) assets.push("Vercel Project Transfer");
  if (listing.hasApiKeys) assets.push("API Keys & Credentials");
  if (listing.hasDesignFiles) assets.push("Design Files");
  if (listing.hasDocumentation) assets.push("Documentation");
  if (listing.hasSocialAccounts) assets.push("Social Media Accounts");
  if (listing.additionalAssets) assets.push(listing.additionalAssets);

  return assets;
}
