/**
 * Local type definitions for Prisma types
 * These mirror the enums defined in prisma/schema.prisma
 * Used as a fallback when Prisma client types aren't generated
 *
 * Using string literal types for compatibility with string assignments
 */

export type ListingStatus =
  | "DRAFT"
  | "PENDING_COLLABORATORS"
  | "PENDING_REVIEW"
  | "ACTIVE"
  | "RESERVED"
  | "SOLD"
  | "EXPIRED"
  | "UNLISTED"
  | "REJECTED";

export const ListingStatus = {
  DRAFT: "DRAFT" as const,
  PENDING_COLLABORATORS: "PENDING_COLLABORATORS" as const,
  PENDING_REVIEW: "PENDING_REVIEW" as const,
  ACTIVE: "ACTIVE" as const,
  RESERVED: "RESERVED" as const,
  SOLD: "SOLD" as const,
  EXPIRED: "EXPIRED" as const,
  UNLISTED: "UNLISTED" as const,
  REJECTED: "REJECTED" as const,
};

export type CollaboratorRole = "PARTNER" | "COLLABORATOR";

export const CollaboratorRole = {
  PARTNER: "PARTNER" as const,
  COLLABORATOR: "COLLABORATOR" as const,
};

export type CollaboratorRoleDescription =
  | "CO_FOUNDER"
  | "DEVELOPER"
  | "TECHNICAL_LEAD"
  | "CTO"
  | "DESIGNER"
  | "MARKETING"
  | "VIDEO_EDITOR"
  | "CONSULTANT"
  | "ADVISOR"
  | "BRANDING"
  | "COPYWRITER"
  | "COMMUNITY_MANAGER"
  | "OTHER";

export const CollaboratorRoleDescription = {
  CO_FOUNDER: "CO_FOUNDER" as const,
  DEVELOPER: "DEVELOPER" as const,
  TECHNICAL_LEAD: "TECHNICAL_LEAD" as const,
  CTO: "CTO" as const,
  DESIGNER: "DESIGNER" as const,
  MARKETING: "MARKETING" as const,
  VIDEO_EDITOR: "VIDEO_EDITOR" as const,
  CONSULTANT: "CONSULTANT" as const,
  ADVISOR: "ADVISOR" as const,
  BRANDING: "BRANDING" as const,
  COPYWRITER: "COPYWRITER" as const,
  COMMUNITY_MANAGER: "COMMUNITY_MANAGER" as const,
  OTHER: "OTHER" as const,
};

export type CollaboratorStatus = "PENDING" | "ACCEPTED" | "DECLINED";

export const CollaboratorStatus = {
  PENDING: "PENDING" as const,
  ACCEPTED: "ACCEPTED" as const,
  DECLINED: "DECLINED" as const,
};

export type ReviewReportReason =
  | "SPAM"
  | "FAKE_REVIEW"
  | "HARASSMENT"
  | "INAPPROPRIATE_CONTENT"
  | "CONFLICT_OF_INTEREST"
  | "FALSE_INFORMATION"
  | "OFF_TOPIC"
  | "OTHER";

export const ReviewReportReason = {
  SPAM: "SPAM" as const,
  FAKE_REVIEW: "FAKE_REVIEW" as const,
  HARASSMENT: "HARASSMENT" as const,
  INAPPROPRIATE_CONTENT: "INAPPROPRIATE_CONTENT" as const,
  CONFLICT_OF_INTEREST: "CONFLICT_OF_INTEREST" as const,
  FALSE_INFORMATION: "FALSE_INFORMATION" as const,
  OFF_TOPIC: "OFF_TOPIC" as const,
  OTHER: "OTHER" as const,
};

export type ApiKeyPermission = "READ" | "WRITE" | "ADMIN" | "TRANSACTION";

export const ApiKeyPermission = {
  READ: "READ" as const,
  WRITE: "WRITE" as const,
  ADMIN: "ADMIN" as const,
  TRANSACTION: "TRANSACTION" as const,
};

export type WebhookEventType =
  | "LISTING_CREATED"
  | "LISTING_UPDATED"
  | "LISTING_ENDED"
  | "LISTING_ENDING_SOON"
  | "BID_PLACED"
  | "BID_OUTBID"
  | "BID_WON"
  | "TRANSACTION_INITIATED"
  | "TRANSACTION_COMPLETED"
  | "TRANSACTION_CANCELLED"
  | "OFFER_RECEIVED"
  | "OFFER_ACCEPTED"
  | "OFFER_REJECTED"
  | "OFFER_COUNTERED"
  | "MESSAGE_RECEIVED"
  | "AGREEMENT_REQUESTED"
  | "AGREEMENT_SIGNED"
  | "WATCHLIST_LISTING_UPDATED"
  | "WATCHLIST_LISTING_ENDING_SOON";

export const WebhookEventType = {
  LISTING_CREATED: "LISTING_CREATED" as const,
  LISTING_UPDATED: "LISTING_UPDATED" as const,
  LISTING_ENDED: "LISTING_ENDED" as const,
  LISTING_ENDING_SOON: "LISTING_ENDING_SOON" as const,
  BID_PLACED: "BID_PLACED" as const,
  BID_OUTBID: "BID_OUTBID" as const,
  BID_WON: "BID_WON" as const,
  TRANSACTION_INITIATED: "TRANSACTION_INITIATED" as const,
  TRANSACTION_COMPLETED: "TRANSACTION_COMPLETED" as const,
  TRANSACTION_CANCELLED: "TRANSACTION_CANCELLED" as const,
  OFFER_RECEIVED: "OFFER_RECEIVED" as const,
  OFFER_ACCEPTED: "OFFER_ACCEPTED" as const,
  OFFER_REJECTED: "OFFER_REJECTED" as const,
  OFFER_COUNTERED: "OFFER_COUNTERED" as const,
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED" as const,
  AGREEMENT_REQUESTED: "AGREEMENT_REQUESTED" as const,
  AGREEMENT_SIGNED: "AGREEMENT_SIGNED" as const,
  WATCHLIST_LISTING_UPDATED: "WATCHLIST_LISTING_UPDATED" as const,
  WATCHLIST_LISTING_ENDING_SOON: "WATCHLIST_LISTING_ENDING_SOON" as const,
};

export type WebhookDeliveryStatus = "PENDING" | "SUCCESS" | "FAILED" | "RETRYING";

export const WebhookDeliveryStatus = {
  PENDING: "PENDING" as const,
  SUCCESS: "SUCCESS" as const,
  FAILED: "FAILED" as const,
  RETRYING: "RETRYING" as const,
};

export type AuthMethod =
  | "WALLET"
  | "PRIVY_EMAIL"
  | "PRIVY_TWITTER"
  | "PRIVY_WALLET";

export const AuthMethod = {
  WALLET: "WALLET" as const,
  PRIVY_EMAIL: "PRIVY_EMAIL" as const,
  PRIVY_TWITTER: "PRIVY_TWITTER" as const,
  PRIVY_WALLET: "PRIVY_WALLET" as const,
};

export type NotificationType =
  | "BID_PLACED"
  | "BID_OUTBID"
  | "AUCTION_WON"
  | "AUCTION_LOST"
  | "AUCTION_ENDING_SOON"
  | "AUCTION_EXTENDED"
  | "TRANSFER_STARTED"
  | "TRANSFER_COMPLETED"
  | "PAYMENT_RECEIVED"
  | "REFUND_PROCESSED"
  | "SALE_CANCELLED"
  | "DISPUTE_OPENED"
  | "DISPUTE_RESOLVED"
  | "REVIEW_RECEIVED"
  | "WATCHLIST_ENDING"
  | "MESSAGE_RECEIVED"
  | "BUYER_INFO_REQUIRED"
  | "BUYER_INFO_REMINDER"
  | "BUYER_INFO_SUBMITTED"
  | "BUYER_INFO_DEADLINE"
  | "FALLBACK_TRANSFER_ACTIVE"
  | "LISTING_RESERVED"
  | "OFFER_ACCEPTED"
  | "COLLABORATION_INVITE"
  | "COLLABORATION_ACCEPTED"
  | "COLLABORATION_DECLINED"
  | "COLLABORATION_REMOVED"
  | "PURCHASE_PARTNER_INVITE"
  | "PURCHASE_PARTNER_DEPOSITED"
  | "PURCHASE_PARTNER_ALL_READY"
  | "PURCHASE_PARTNER_TIMEOUT"
  | "PURCHASE_PARTNER_LEAD_TRANSFERRED"
  | "REFERRAL_EARNED"
  | "AGREEMENT_REQUESTED"
  | "AGREEMENT_SIGNED"
  | "SYSTEM";

export const NotificationType = {
  BID_PLACED: "BID_PLACED" as const,
  BID_OUTBID: "BID_OUTBID" as const,
  AUCTION_WON: "AUCTION_WON" as const,
  AUCTION_LOST: "AUCTION_LOST" as const,
  AUCTION_ENDING_SOON: "AUCTION_ENDING_SOON" as const,
  AUCTION_EXTENDED: "AUCTION_EXTENDED" as const,
  TRANSFER_STARTED: "TRANSFER_STARTED" as const,
  TRANSFER_COMPLETED: "TRANSFER_COMPLETED" as const,
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED" as const,
  REFUND_PROCESSED: "REFUND_PROCESSED" as const,
  SALE_CANCELLED: "SALE_CANCELLED" as const,
  DISPUTE_OPENED: "DISPUTE_OPENED" as const,
  DISPUTE_RESOLVED: "DISPUTE_RESOLVED" as const,
  REVIEW_RECEIVED: "REVIEW_RECEIVED" as const,
  WATCHLIST_ENDING: "WATCHLIST_ENDING" as const,
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED" as const,
  BUYER_INFO_REQUIRED: "BUYER_INFO_REQUIRED" as const,
  BUYER_INFO_REMINDER: "BUYER_INFO_REMINDER" as const,
  BUYER_INFO_SUBMITTED: "BUYER_INFO_SUBMITTED" as const,
  BUYER_INFO_DEADLINE: "BUYER_INFO_DEADLINE" as const,
  FALLBACK_TRANSFER_ACTIVE: "FALLBACK_TRANSFER_ACTIVE" as const,
  LISTING_RESERVED: "LISTING_RESERVED" as const,
  OFFER_ACCEPTED: "OFFER_ACCEPTED" as const,
  COLLABORATION_INVITE: "COLLABORATION_INVITE" as const,
  COLLABORATION_ACCEPTED: "COLLABORATION_ACCEPTED" as const,
  COLLABORATION_DECLINED: "COLLABORATION_DECLINED" as const,
  COLLABORATION_REMOVED: "COLLABORATION_REMOVED" as const,
  PURCHASE_PARTNER_INVITE: "PURCHASE_PARTNER_INVITE" as const,
  PURCHASE_PARTNER_DEPOSITED: "PURCHASE_PARTNER_DEPOSITED" as const,
  PURCHASE_PARTNER_ALL_READY: "PURCHASE_PARTNER_ALL_READY" as const,
  PURCHASE_PARTNER_TIMEOUT: "PURCHASE_PARTNER_TIMEOUT" as const,
  PURCHASE_PARTNER_LEAD_TRANSFERRED: "PURCHASE_PARTNER_LEAD_TRANSFERRED" as const,
  REFERRAL_EARNED: "REFERRAL_EARNED" as const,
  AGREEMENT_REQUESTED: "AGREEMENT_REQUESTED" as const,
  AGREEMENT_SIGNED: "AGREEMENT_SIGNED" as const,
  SYSTEM: "SYSTEM" as const,
};
