ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "tokenImage" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "tokenDescription" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "dbcPoolAddress" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "dbcConfigKey" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "graduationThreshold" DECIMAL(18, 8) NOT NULL DEFAULT 85;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "graduatedAt" TIMESTAMP(3);
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "dammPoolAddress" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "migrationFeeOption" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "tradingFeeBps" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "creatorFeePct" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "partnerLockedLpPct" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "creatorLockedLpPct" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "creatorWallet" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "vanityKeypair" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "totalBondingCurveFeesSOL" DECIMAL(18, 8) NOT NULL DEFAULT 0;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "totalPostGradFeesSOL" DECIMAL(18, 8) NOT NULL DEFAULT 0;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "creatorFeesClaimedSOL" DECIMAL(18, 8) NOT NULL DEFAULT 0;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "platformFeesClaimedSOL" DECIMAL(18, 8) NOT NULL DEFAULT 0;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "transactionId" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "listingId" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "twitter" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "telegram" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "discord" TEXT;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "TokenLaunch" ADD COLUMN IF NOT EXISTS "bondingCurveStatus" "BondingCurveStatus" NOT NULL DEFAULT 'PENDING';
CREATE INDEX IF NOT EXISTS "TokenLaunch_status_idx" ON "TokenLaunch"("status");
CREATE INDEX IF NOT EXISTS "TokenLaunch_transactionId_idx" ON "TokenLaunch"("transactionId");
CREATE INDEX IF NOT EXISTS "TokenLaunch_listingId_idx" ON "TokenLaunch"("listingId");
CREATE INDEX IF NOT EXISTS "TokenLaunch_bondingCurveStatus_idx" ON "TokenLaunch"("bondingCurveStatus");
CREATE INDEX IF NOT EXISTS "TokenLaunch_tokenMint_idx" ON "TokenLaunch"("tokenMint");
CREATE INDEX IF NOT EXISTS "TokenLaunch_creatorWallet_idx" ON "TokenLaunch"("creatorWallet");
SELECT table_name, column_name, data_type FROM information_schema.columns WHERE table_name = 'TokenLaunch' ORDER BY ordinal_position;
